name: Tutorialreloaded
version: 1.0-SNAPSHOT
main: de.monaco07.tutorialreloaded.Main
api-version: 1.16
authors: [ monaco07 ]
description: erstes plugin
website: meinhub.netlify.app

commands:
  timer:
    permission: tutorialreloaded.command.timer
  backpack:
    aliases: [ bp ]